name: my_app
description: Pursuade
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animated_flip_counter: ^0.3.4
  equatable: ^2.0.7
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_confetti: ^0.5.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  intl:
  latext: ^0.5.1
  logger: ^2.5.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  rive: ^0.13.20
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/questions.json
    - assets/lotties/
    - assets/svgs/

  fonts:
    - family: CascadiaCode
      fonts:
        - asset: assets/fonts/CascadiaCode-Regular.ttf
          weight: 300
        - asset: assets/fonts/CascadiaCode-Medium.ttf
          weight: 400
        - asset: assets/fonts/CascadiaCode-Bold.ttf
          weight: 700
